feat(prestop): gracefully shut down spdk_tgt
Longhorn 11760

Signed-off-by: Derek Su <derek.su@suse.com>

diff --git a/package/instance-manager-v2-prestop b/package/instance-manager-v2-prestop
--- a/package/instance-manager-v2-prestop
+++ b/package/instance-manager-v2-prestop
@@ -1,29 +1,46 @@
 #!/bin/bash
 
+log() {
+    echo "$(date '+%Y-%m-%d %H:%M:%S.%N') $*"
+}
+
 function cleanup_spdk_resources() {
-    echo "Caught termination signal. Cleaning up SPDK resources..."
+    log "Caught termination signal. Cleaning up SPDK resources..."
 
     local v2_devices=($(get_v2_devices))
     for device in "${v2_devices[@]}"; do
         dmsetup remove "$device"
-        echo "Removed device-mapper device: $device"
+        log "Removed device-mapper device: $device"
 
         device_file="/host/dev/longhorn/$device"
         rm "$device_file"
-        echo "Removed device file: $device_file"
+        log "Removed device file: $device_file"
     done
+
+    log "Sending SIGTERM to go-spdk-helper to stop spdk_tgt..."
+    go-spdk-helper kill-instance --sig-name SIGTERM
+    if [[ $? -ne 0 ]]; then
+        log "Failed to send SIGTERM to go-spdk-helper"
+    else
+        log "Successfully sent SIGTERM to go-spdk-helper"
+    fi
 }
 
 function get_v2_devices() {
-    local dm_devices=$(dmsetup ls | awk '{print $1}')
-    local device_files=$(ls /host/dev/longhorn/)
+    local dm_devices
+    dm_devices=$(dmsetup ls 2>/dev/null | awk '{print $1}')
     local v2_devices=()
 
-    # Iterate over DM devices.
+    if [[ ! -d /host/dev/longhorn/ ]]; then
+        echo "${v2_devices[@]}"
+        return
+    fi
+
+    local device_files
+    device_files=$(ls /host/dev/longhorn/)
+
     for dm_device in $dm_devices; do
-        # Iterate over Longhorn device files.
         for device_file in $device_files; do
-            # If the DM device matches the Longhorn device file, add it to the V2 devices list.
             if [[ "$dm_device" == "$device_file" ]]; then
                 v2_devices+=("$dm_device")
                 break
